# MegaLinter GitHub Action configuration file (Dry Run)
---
name: MegaLinter

on:
  push:
  pull_request:
    branches:
      - main
      - master

env:
  APPLY_FIXES: none  # Ensures no automatic fixes
  VALIDATE_ALL_CODEBASE: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: MegaLinter Dry Run
    runs-on: ubuntu-latest

    permissions:
      contents: read   # No write permissions needed
      issues: read
      pull-requests: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run MegaLinter (Dry Run)
        uses: oxsecurity/megalinter/flavors/terraform@v8
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive MegaLinter Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter Reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log
